[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo-console = "0.2.3"
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
